#!/bin/sh
# 1. Apply Black to all staged Python files
black $(git diff --staged --name-only --relative -- '*.py' 2>/dev/null) --quiet 2>/dev/null
# 2. Apply isort to all staged Python files
isort $(git diff --staged --name-only --relative -- '*.py' 2>/dev/null) --quiet --profile black 2>/dev/null
# 3. Update commit
git update-index --again
